name: Build Microblog

on:
  push:
    paths:
      - "posts/*.md"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: pip install markdown
      - run: python build.py
      - run: |
          git config --global user.name "Auto Blogger"
          git config --global user.email "bot@example.com"
          git add index.html
          git commit -m "Build blog"
          git push
